[loggers]
keys=root,MXLogger,PyralLogger

[logger_PyralLogger]
level=WARNING
handlers=fileHandler
qualname=pyral
propagate=0

[handlers]
keys=fileHandler, consoleHandler, consoleHandlerUser, consoleHandlerTable

[formatters]
keys=MXFormatter, MXFormatterUser

[logger_root]
level=DEBUG
handlers=fileHandler, consoleHandlerUser, consoleHandlerTable

[logger_MXLogger]
level=DEBUG
handlers=fileHandler, consoleHandlerUser, consoleHandlerTable
qualname=MXLogger
propagate=0

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=MXFormatter
args=('mx.log', 'w')

[handler_consoleHandlerUser]
class=StreamHandler
level=DEBUG
formatter=MXFormatterUser
args=(sys.stderr,)

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=MXFormatter
args=(sys.stderr,)

[handler_consoleHandlerTable]
class=StreamHandler
level=DEBUG
formatter=MXFormatterUser
args=(sys.stdout,)

[formatter_MXFormatter]
class=log_table_config.TableAwareFormatter
format= MX: %(name)s - %(levelname)s - %(message)s

[formatter_MXFormatterUser]
class=log_table_config.TableAwareFormatter
format=MX: %(name)s - %(levelname)s - %(message)s