""" traverse.py  -- execute a traverse action """

# System
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from mx.method import Method  # TOOD: Replace with Activity after refactoring State/Assigner Activities

# Model Integration
from pyral.relation import Relation

# MX
from mx.db_names import mmdb
from mx.actions.action import Action


class Traverse(Action):

    def __init__(self, action_id: str, activity: "Method"):
        """

        :param action_id:
        :param activity:
        """
        super().__init__(anum=activity.anum, action_id=action_id)

        Relation.join(db=mmdb, rname1=activity.method_rvname, rname2="Traverse_Action")

        # Find my action
        R = f"ID:<{action_id}>"
        Relation.restrict(db=mmdb, restriction=R)
        trav_action_flows_t = Relation.project(db=mmdb, attributes=("Path", "Source_flow", "Destination_flow"))

        # perform a series of semi-joins following the path
        # set value of destination flow with the relation name (generated by RVN)

        pass

        # R = f"Phrase:<{phrase}>, Domain:<{cls.domain}>"
        # result = Relation.restrict(db=db, relation='Perspective', restriction=R)


